### ISSUE TITLE
delegate registration issue 

### ISSUE THREAD

**Issue by majidrajabi** [harness/harness-cd-community#48]
Using this docker compose https://github.com/harness/harness-cd-community/blob/main/docker-compose/harness/docker-compose.yml to create harness-cd-community instances. Then try to create a kubernetes delegate. After the delegate pod was created the readiness probe is failed (test -s delegate.log) and the log shows nothing related.
![image](https://user-images.githubusercontent.com/32163679/156382653-be5352cf-7dff-4dfd-80ad-bb461222969d.png)

I remove this probe manually and the pod state turns to ready 1/1 but the connection problem still there! 
![image](https://user-images.githubusercontent.com/32163679/156383036-a5f19dde-6529-45b4-8608-a89af68920c1.png)

minikube version: v1.25.1
docker Version:   20.10.12
delegate manifest : 
```
apiVersion: v1
kind: Namespace
metadata:
  name: harness-delegate-ng

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harness-delegate-ng-cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: harness-delegate-ng
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: test-del-proxy
  namespace: harness-delegate-ng
type: Opaque
data:
  # Enter base64 encoded username and password, if needed
  PROXY_USER: ""
  PROXY_PASSWORD: ""

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    harness.io/name: test-del
  name: test-del
  namespace: harness-delegate-ng
spec:
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      harness.io/name: test-del
  serviceName: ""
  template:
    metadata:
      labels:
        harness.io/name: test-del
    spec:
      containers:
      - image: harness/delegate:latest
        imagePullPolicy: Always
        name: harness-delegate-instance
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "2048Mi"
          requests:
            cpu: "0.5"
            memory: "2048Mi"
        readinessProbe:
          exec:
            command:
              - test
              - -s
              - delegate.log
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - bash
              - -c
              - '[[ -e /opt/harness-delegate/msg/data/watcher-data && $(($(date +%s000) - $(grep heartbeat /opt/harness-delegate/msg/data/watcher-data | cut -d ":" -f 2 | cut -d "," -f 1))) -lt 300000 ]]'
          initialDelaySeconds: 240
          periodSeconds: 10
          failureThreshold: 2
        env:
        - name: JAVA_OPTS
          value: "-Xms64M"
        - name: ACCOUNT_ID
          value: HzTVQzAaTLmr3UWrZGQ_Ww
        - name: ACCOUNT_SECRET
          value: 404610ff418f6e5f13280d3845c67d5d
        - name: MANAGER_HOST_AND_PORT
          value: http://192.168.109.1
        - name: DEPLOY_MODE
          value: KUBERNETES_ONPREM
        - name: DELEGATE_NAME
          value: test-del
        - name: DELEGATE_TYPE
          value: "KUBERNETES"
        - name: PROXY_HOST
          value: ""
        - name: PROXY_PORT
          value: ""
        - name: PROXY_SCHEME
          value: ""
        - name: NO_PROXY
          value: ""
        - name: PROXY_MANAGER
          value: "true"
        - name: PROXY_USER
          valueFrom:
            secretKeyRef:
              name: test-del-proxy
              key: PROXY_USER
        - name: PROXY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-del-proxy
              key: PROXY_PASSWORD
        - name: POLL_FOR_TASKS
          value: "false"
        - name: ENABLE_CE
          value: "false"
        - name: GRPC_SERVICE_ENABLED
          value: "true"
        - name: GRPC_SERVICE_CONNECTOR_PORT
          value: "8080"
        - name: DELEGATE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DELEGATE_DESCRIPTION
          value: ""
        - name: DELEGATE_TAGS
          value: ""
        - name: DELEGATE_ORG_IDENTIFIER
          value: "default"
        - name: DELEGATE_PROJECT_IDENTIFIER
          value: "test"
        - name: INIT_SCRIPT
          value: ""
        - name: NEXT_GEN
          value: "true"
        - name: WATCHER_STORAGE_URL
          value: http://192.168.109.1/storage/wingswatchers
        - name: WATCHER_CHECK_LOCATION
          value: watcherprod.txt
        - name: REMOTE_WATCHER_URL_CDN
          value: https://qa.harness.io/public/shared/watchers/builds
        - name: DELEGATE_STORAGE_URL
          value: http://192.168.109.1/storage/wingsdelegates
        - name: DELEGATE_CHECK_LOCATION
          value: delegateprod.txt
        - name: HELM_DESIRED_VERSION
          value: ""
        - name: USE_CDN
          value: "false"
        - name: CDN_URL
          value: https://qa.harness.io
        - name: JRE_VERSION
          value: 1.8.0_242
        - name: HELM3_PATH
          value: ""
        - name: HELM_PATH
          value: ""
        - name: KUSTOMIZE_PATH
          value: ""
        - name: KUBECTL_PATH
          value: ""
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: delegate-service
  namespace: harness-delegate-ng
spec:
  type: ClusterIP
  selector:
    harness.io/name: test-del
  ports:
    - port: 8080
```

What is going wrong?
